using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace App2.Types;

[JsonSerializable(typeof(List<VlastnictviData>), TypeInfoPropertyName = "VlastnictviDataList")]
[JsonSerializable(typeof(VlastnictviData))]
[JsonSerializable(typeof(List<UcastnikRizeniData>), TypeInfoPropertyName = "UcastnikRizeniDataList")]
[JsonSerializable(typeof(UcastnikRizeniData))]
[JsonSerializable(typeof(List<UcastData>), TypeInfoPropertyName = "UcastDataList")]
[JsonSerializable(typeof(UcastData))]
[JsonSerializable(typeof(List<TypUcastnikaData>), TypeInfoPropertyName = "TypUcastnikaDataList")]
[JsonSerializable(typeof(TypUcastnikaData))]
[JsonSerializable(typeof(List<TypRizeniData>), TypeInfoPropertyName = "TypRizeniDataList")]
[JsonSerializable(typeof(TypRizeniData))]
[JsonSerializable(typeof(List<TypOperaceData>), TypeInfoPropertyName = "TypOperaceDataList")]
[JsonSerializable(typeof(TypOperaceData))]
[JsonSerializable(typeof(List<RizeniOperaceRowData>), TypeInfoPropertyName = "RizeniOperaceRowDataList")]
[JsonSerializable(typeof(RizeniOperaceRowData))]
[JsonSerializable(typeof(List<RizeniData>), TypeInfoPropertyName = "RizeniDataList")]
[JsonSerializable(typeof(RizeniData))]
[JsonSerializable(typeof(List<PlombaData>), TypeInfoPropertyName = "PlombaDataList")]
[JsonSerializable(typeof(PlombaData))]
[JsonSerializable(typeof(List<ParcelaRowData>), TypeInfoPropertyName = "ParcelaRowDataList")]
[JsonSerializable(typeof(ParcelaRowData))]
[JsonSerializable(typeof(List<OkresData>), TypeInfoPropertyName = "OkresDataList")]
[JsonSerializable(typeof(OkresData))]
[JsonSerializable(typeof(List<ObecData>), TypeInfoPropertyName = "ObecDataList")]
[JsonSerializable(typeof(ObecData))]
[JsonSerializable(typeof(List<MajitelData>), TypeInfoPropertyName = "MajitelDataList")]
[JsonSerializable(typeof(MajitelData))]
[JsonSerializable(typeof(List<ListVlastnictviData>), TypeInfoPropertyName = "ListVlastnictviDataList")]
[JsonSerializable(typeof(ListVlastnictviData))]
[JsonSerializable(typeof(List<KrajData>), TypeInfoPropertyName = "KrajDataList")]
[JsonSerializable(typeof(KrajData))]
[JsonSerializable(typeof(List<KatastralniUzemiData>), TypeInfoPropertyName = "KatastralniUzemiDataList")]
[JsonSerializable(typeof(KatastralniUzemiData))]
[JsonSerializable(typeof(List<BremenoParcelaParcelaData>), TypeInfoPropertyName = "BremenoParcelaParcelaDataList")]
[JsonSerializable(typeof(BremenoParcelaParcelaData))]
[JsonSerializable(typeof(List<BremenoParcelaMajitelData>), TypeInfoPropertyName = "BremenoParcelaMajitelDataList")]
[JsonSerializable(typeof(BremenoParcelaMajitelData))]
[JsonSerializable(typeof(List<BpejData>), TypeInfoPropertyName = "BpejDataList")]
[JsonSerializable(typeof(BpejData))]
[JsonSerializable(typeof(LVData))]
[JsonSerializable(typeof(SpravniRizeniData))]
[JsonSerializable(typeof(List<ParcelaData>), TypeInfoPropertyName = "ParcelaDataList")]
[JsonSerializable(typeof(ParcelaData))]
public partial class AppJsonContext : JsonSerializerContext
{
}
